In [ ]:
import pandas as pd
import numpy as np
import pickle
import pandas_profiling as pp
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/wesad-classification-hrv-train-dataset.csv')
test = pd.read_csv('/content/drive/MyDrive/wesad-classification-hrv-test-dataset.csv')

In [ ]:
train

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,MEAN_RR_MEAN_MEAN_REL_RR,SD2_LF,HR_LF,HR_HF,HF_VLF,subject id,condition,SSSQ class,SSSQ Label,condition label
0,860.758450,858.389130,75.161448,14.461513,14.460581,5.197343,70.242263,6.25,0.75,10.238012,...,-5.208054e+06,0.137408,0.091228,3.666502,0.009514,7,baseline,low,0,0
1,1044.449374,1036.796500,82.209648,22.516679,22.515843,3.651056,57.792396,28.50,2.25,15.941094,...,4.953282e+06,0.059868,0.030044,25.537614,0.001175,4,baseline,low,0,0
2,510.072193,503.341590,32.094249,8.549018,8.547740,3.754145,118.059988,3.50,0.00,6.051753,...,-1.685542e+06,0.127065,0.333489,3.031509,0.084238,13,stress,medium,1,2
3,930.296969,940.394165,59.089578,7.816167,7.814190,7.559917,64.769049,0.00,0.00,5.532404,...,5.520502e+06,0.505268,0.392480,11.410422,0.004625,5,baseline,high,2,0
4,692.067906,687.546285,47.584437,6.487698,6.487256,7.334564,87.096547,0.00,0.00,4.592942,...,6.091203e+06,0.248241,0.322039,19.549568,0.003409,5,stress,high,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108515,749.434911,744.009250,64.790097,10.188321,10.184029,6.359252,80.640911,3.25,0.00,7.210237,...,-1.795373e+06,0.176761,0.156051,3.711716,0.010302,15,baseline,medium,1,0
108516,699.731792,694.278245,52.669920,13.735290,13.732733,3.834642,86.216287,7.75,0.25,9.722700,...,-2.751756e+06,0.124832,0.145737,0.705795,0.166195,15,stress,medium,1,2
108517,524.960265,517.460805,30.945793,7.222979,7.221443,4.284353,114.670177,0.50,0.00,5.112742,...,3.118196e+06,0.098574,0.260064,4.994050,0.137364,14,stress,high,2,2
108518,708.073163,702.006530,47.784108,7.904278,7.897932,6.045347,85.099063,1.75,0.00,5.591693,...,1.583340e+06,0.211085,0.266733,5.968401,0.028522,13,baseline,medium,1,0
108519,819.493935,801.341050,82.270680,17.229690,17.228443,4.774937,73.922886,14.75,0.50,12.197644,...,-3.012433e+06,0.094450,0.060342,2.892343,0.009337,7,baseline,low,0,0

In [ ]:
test

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,MEAN_RR_MEAN_MEAN_REL_RR,SD2_LF,HR_LF,HR_HF,HF_VLF,subject id,condition,SSSQ class,SSSQ Label,condition label
0,856.640559,855.196440,63.543133,15.490732,15.490690,4.102010,70.436793,9.75,0.0,10.967324,...,-1.241198e+07,0.083708,0.066106,2.156205,0.031908,8,baseline,medium,1,0
1,911.890969,914.313935,49.739529,11.485676,11.485584,4.330570,65.996032,3.50,0.0,8.131731,...,3.087452e+07,0.142285,0.134394,9.215434,0.005218,6,baseline,medium,1,0
2,505.424097,500.162060,27.207534,5.217502,5.216857,5.214666,119.049905,0.00,0.0,3.693507,...,-4.138619e+06,0.180380,0.560690,8.795038,0.072400,11,stress,high,2,2
3,976.606489,976.392520,93.145519,24.999690,24.999508,3.725867,62.014311,32.25,4.0,17.699516,...,-8.913369e+06,0.058028,0.027568,9.998307,0.002822,17,baseline,low,0,0
4,740.323476,729.095405,73.676039,10.740166,10.739891,6.859860,81.833707,3.75,0.0,7.603784,...,-5.150339e+06,0.193675,0.152519,5.783011,0.004499,15,baseline,medium,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13560,823.312502,822.335095,52.926006,15.580839,15.579649,3.396865,73.177890,8.50,0.0,11.030307,...,-3.656790e+06,0.058746,0.058068,3.095154,0.029057,11,baseline,low,0,0
13561,813.487251,812.393075,36.414421,11.722249,11.719850,3.106436,73.905611,3.50,0.0,8.297590,...,2.498761e+06,0.134053,0.194929,1.471170,0.171440,14,baseline,high,2,0
13562,1038.999403,1031.351750,90.367195,26.508801,26.507248,3.408951,58.174854,34.75,5.5,18.766987,...,-2.669341e+06,0.051203,0.023563,13.195805,0.001831,4,baseline,low,0,0
13563,716.291740,714.843350,41.201263,5.528628,5.522179,7.452348,84.037013,0.00,0.0,3.909673,...,-1.867412e+06,0.549884,0.794870,12.422019,0.011508,5,stress,high,2,2
13564,837.392090,828.990555,47.989568,14.685813,14.684598,3.267750,71.878852,8.00,0.0,10.396616,...,-2.727486e+06,0.091768,0.098353,2.141237,0.066046,8,baseline,medium,1,0

In [ ]:
train['condition'].unique()

array(['baseline', 'stress', 'amusement'], dtype=object)

In [ ]:
conditions = dict(train['condition'].value_counts())
labels = list(conditions.keys())
counts = list(conditions.values())
plt.bar(labels,counts, color ='green',
        width = 0.4)
plt.show()

In [ ]:
le = preprocessing.LabelEncoder()
le.fit(train['condition'])
train['condition'] = le.transform(train['condition'])
test['condition'] = le.transform(test['condition'])

In [ ]:
train

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,MEAN_RR_MEAN_MEAN_REL_RR,SD2_LF,HR_LF,HR_HF,HF_VLF,subject id,condition,SSSQ class,SSSQ Label,condition label
0,860.758450,858.389130,75.161448,14.461513,14.460581,5.197343,70.242263,6.25,0.75,10.238012,...,-5.208054e+06,0.137408,0.091228,3.666502,0.009514,7,1,low,0,0
1,1044.449374,1036.796500,82.209648,22.516679,22.515843,3.651056,57.792396,28.50,2.25,15.941094,...,4.953282e+06,0.059868,0.030044,25.537614,0.001175,4,1,low,0,0
2,510.072193,503.341590,32.094249,8.549018,8.547740,3.754145,118.059988,3.50,0.00,6.051753,...,-1.685542e+06,0.127065,0.333489,3.031509,0.084238,13,2,medium,1,2
3,930.296969,940.394165,59.089578,7.816167,7.814190,7.559917,64.769049,0.00,0.00,5.532404,...,5.520502e+06,0.505268,0.392480,11.410422,0.004625,5,1,high,2,0
4,692.067906,687.546285,47.584437,6.487698,6.487256,7.334564,87.096547,0.00,0.00,4.592942,...,6.091203e+06,0.248241,0.322039,19.549568,0.003409,5,2,high,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108515,749.434911,744.009250,64.790097,10.188321,10.184029,6.359252,80.640911,3.25,0.00,7.210237,...,-1.795373e+06,0.176761,0.156051,3.711716,0.010302,15,1,medium,1,0
108516,699.731792,694.278245,52.669920,13.735290,13.732733,3.834642,86.216287,7.75,0.25,9.722700,...,-2.751756e+06,0.124832,0.145737,0.705795,0.166195,15,2,medium,1,2
108517,524.960265,517.460805,30.945793,7.222979,7.221443,4.284353,114.670177,0.50,0.00,5.112742,...,3.118196e+06,0.098574,0.260064,4.994050,0.137364,14,2,high,2,2
108518,708.073163,702.006530,47.784108,7.904278,7.897932,6.045347,85.099063,1.75,0.00,5.591693,...,1.583340e+06,0.211085,0.266733,5.968401,0.028522,13,1,medium,1,0
108519,819.493935,801.341050,82.270680,17.229690,17.228443,4.774937,73.922886,14.75,0.50,12.197644,...,-3.012433e+06,0.094450,0.060342,2.892343,0.009337,7,1,low,0,0

In [ ]:
corr = train.corr()

In [ ]:
def feature_selection(correlation,threshold):
    selected_features = []
    for i in range(corr.shape[0]):
      if corr.iloc[i,35] > threshold:
        selected_features.append(train.iloc[:,i])
    return pd.DataFrame(selected_features).T

In [ ]:
#Selecting features having a correlation coefficient greater than 1
CORRELATION_THRESHOLD = 0.1
reduced_train = feature_selection(corr,CORRELATION_THRESHOLD)

In [ ]:
train

,MEAN_RR,MEDIAN_RR,SDRR,RMSSD,SDSD,SDRR_RMSSD,HR,pNN25,pNN50,SD1,...,MEAN_RR_MEAN_MEAN_REL_RR,SD2_LF,HR_LF,HR_HF,HF_VLF,subject id,condition,SSSQ class,SSSQ Label,condition label
0,860.758450,858.389130,75.161448,14.461513,14.460581,5.197343,70.242263,6.25,0.75,10.238012,...,-5.208054e+06,0.137408,0.091228,3.666502,0.009514,7,1,low,0,0
1,1044.449374,1036.796500,82.209648,22.516679,22.515843,3.651056,57.792396,28.50,2.25,15.941094,...,4.953282e+06,0.059868,0.030044,25.537614,0.001175,4,1,low,0,0
2,510.072193,503.341590,32.094249,8.549018,8.547740,3.754145,118.059988,3.50,0.00,6.051753,...,-1.685542e+06,0.127065,0.333489,3.031509,0.084238,13,2,medium,1,2
3,930.296969,940.394165,59.089578,7.816167,7.814190,7.559917,64.769049,0.00,0.00,5.532404,...,5.520502e+06,0.505268,0.392480,11.410422,0.004625,5,1,high,2,0
4,692.067906,687.546285,47.584437,6.487698,6.487256,7.334564,87.096547,0.00,0.00,4.592942,...,6.091203e+06,0.248241,0.322039,19.549568,0.003409,5,2,high,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108515,749.434911,744.009250,64.790097,10.188321,10.184029,6.359252,80.640911,3.25,0.00,7.210237,...,-1.795373e+06,0.176761,0.156051,3.711716,0.010302,15,1,medium,1,0
108516,699.731792,694.278245,52.669920,13.735290,13.732733,3.834642,86.216287,7.75,0.25,9.722700,...,-2.751756e+06,0.124832,0.145737,0.705795,0.166195,15,2,medium,1,2
108517,524.960265,517.460805,30.945793,7.222979,7.221443,4.284353,114.670177,0.50,0.00,5.112742,...,3.118196e+06,0.098574,0.260064,4.994050,0.137364,14,2,high,2,2
108518,708.073163,702.006530,47.784108,7.904278,7.897932,6.045347,85.099063,1.75,0.00,5.591693,...,1.583340e+06,0.211085,0.266733,5.968401,0.028522,13,1,medium,1,0
108519,819.493935,801.341050,82.270680,17.229690,17.228443,4.774937,73.922886,14.75,0.50,12.197644,...,-3.012433e+06,0.094450,0.060342,2.892343,0.009337,7,1,low,0,0

In [ ]:
cond = np.array(train['condition'])

In [ ]:
len(cond)

108520

In [ ]:
reduced_train['condition'] = cond

In [ ]:
reduced_train

,SDRR,SDRR_RMSSD,HR,SD2,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_RMSSD_REL_RR,SKEW_REL_RR,VLF,...,VLF_LOG,HF_LOG,SDRR_RMSSD_LOG,SKEW_YEO_JONSON,MEAN_REL_RR_YEO_JONSON,SKEW_REL_RR_YEO_JONSON,HR_SQRT,subject id,SSSQ Label,condition
0,75.161448,5.197343,70.242263,105.800140,0.053677,-0.000165,-0.000286,2.104142,0.053677,2013.584521,...,7.608168,3.003593,1.824121,0.053188,-0.000167,0.053188,8.381066,7.0,0.0,1
1,82.209648,3.651056,57.792396,115.163944,0.578705,0.000211,-0.000638,2.217618,0.578705,1926.201330,...,7.563824,1.182656,1.537094,0.671867,0.000211,0.671867,7.602131,4.0,0.0,1
2,32.094249,3.754145,118.059988,44.982862,1.623759,-0.000303,0.000003,1.254616,1.623759,462.314125,...,6.138405,3.687486,1.559017,2.004587,-0.000304,2.004587,10.865541,13.0,1.0,2
3,59.089578,7.559917,64.769049,83.381947,-0.596994,0.000169,-0.000397,1.998056,-0.596994,1227.245560,...,7.113342,1.898565,2.147091,-0.636446,0.000168,-0.636446,8.047922,5.0,2.0,1
4,47.584437,7.334564,87.096547,67.137636,0.491406,0.000114,0.001556,2.869915,0.491406,1306.992460,...,7.176249,1.696563,2.120411,0.465961,0.000113,0.465961,9.332553,5.0,2.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108515,64.790097,6.359252,80.640911,91.342902,0.537476,-0.000417,0.001967,1.975884,0.537476,2108.871294,...,7.654382,3.123512,1.995958,0.551901,-0.000419,0.551901,8.980028,15.0,1.0,1
108516,52.669920,3.834642,86.216287,73.849239,0.689209,-0.000254,0.000514,1.304745,0.689209,735.010197,...,6.601244,4.813442,1.575807,0.712169,-0.000255,0.712169,9.285273,15.0,1.0,2
108517,30.945793,4.284353,114.670177,43.464285,1.075835,0.000168,0.000180,1.277589,1.075835,167.157071,...,5.124898,3.176442,1.664750,0.871848,0.000166,0.871848,10.708416,14.0,2.0,2
108518,47.784108,6.045347,85.099063,67.345193,1.209226,0.000447,0.001132,2.035208,1.209226,499.906069,...,6.216419,2.725122,1.952367,1.431071,0.000445,1.431071,9.224915,13.0,1.0,1
108519,82.270680,4.774937,73.922886,115.707160,0.661252,-0.000272,-0.000227,2.178320,0.661252,2737.158224,...,7.915041,3.279336,1.753527,0.601742,-0.000276,0.601742,8.597842,7.0,0.0,1

Split into X and y

In [ ]:
X_train = reduced_train.iloc[:,:-1]
y_train = reduced_train.iloc[:,-1]

In [ ]:
X_test = test[X_train.columns]
y_test = test['condition']

In [ ]:
X_train.head()

,SDRR,SDRR_RMSSD,HR,SD2,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_RMSSD_REL_RR,SKEW_REL_RR,VLF,...,MEDIAN_REL_RR_LOG,VLF_LOG,HF_LOG,SDRR_RMSSD_LOG,SKEW_YEO_JONSON,MEAN_REL_RR_YEO_JONSON,SKEW_REL_RR_YEO_JONSON,HR_SQRT,subject id,SSSQ Label
0,75.161448,5.197343,70.242263,105.800140,0.053677,-0.000165,-0.000286,2.104142,0.053677,2013.584521,...,-0.000286,7.608168,3.003593,1.824121,0.053188,-0.000167,0.053188,8.381066,7.0,0.0
1,82.209648,3.651056,57.792396,115.163944,0.578705,0.000211,-0.000638,2.217618,0.578705,1926.201330,...,-0.000638,7.563824,1.182656,1.537094,0.671867,0.000211,0.671867,7.602131,4.0,0.0
2,32.094249,3.754145,118.059988,44.982862,1.623759,-0.000303,0.000003,1.254616,1.623759,462.314125,...,0.000003,6.138405,3.687486,1.559017,2.004587,-0.000304,2.004587,10.865541,13.0,1.0
3,59.089578,7.559917,64.769049,83.381947,-0.596994,0.000169,-0.000397,1.998056,-0.596994,1227.245560,...,-0.000397,7.113342,1.898565,2.147091,-0.636446,0.000168,-0.636446,8.047922,5.0,2.0
4,47.584437,7.334564,87.096547,67.137636,0.491406,0.000114,0.001556,2.869915,0.491406,1306.992460,...,0.001555,7.176249,1.696563,2.120411,0.465961,0.000113,0.465961,9.332553,5.0,2.0

In [ ]:
y_train.head()

0    1
1    1
2    2
3    1
4    2
Name: condition, dtype: int64

In [ ]:
X_test.head()

,SDRR,SDRR_RMSSD,HR,SD2,SKEW,MEAN_REL_RR,MEDIAN_REL_RR,SDRR_RMSSD_REL_RR,SKEW_REL_RR,VLF,...,MEDIAN_REL_RR_LOG,VLF_LOG,HF_LOG,SDRR_RMSSD_LOG,SKEW_YEO_JONSON,MEAN_REL_RR_YEO_JONSON,SKEW_REL_RR_YEO_JONSON,HR_SQRT,subject id,SSSQ Label
0,63.543133,4.102010,70.436793,89.191801,-0.102585,-0.000069,-0.002450,1.970623,-0.102585,1023.799120,...,-0.002453,6.932252,3.516519,1.629635,-0.101676,-0.000069,-0.101676,8.392663,8,1
1,49.739529,4.330570,65.996032,69.870712,-0.178860,0.000030,-0.000799,2.166519,-0.178860,1372.472455,...,-0.000799,7.225097,2.099424,1.673458,-0.175197,0.000030,-0.175197,8.123794,6,1
2,27.207534,5.214666,119.049905,38.299581,0.431171,-0.000122,0.000281,1.245031,0.431171,186.962752,...,0.000281,5.236244,2.676630,1.826912,0.434722,-0.000123,0.434722,10.910999,11,2
3,93.145519,3.725867,62.014311,130.533147,-0.127575,-0.000110,0.002974,2.311054,-0.127575,2197.685692,...,0.002970,7.695615,1.974426,1.553051,-0.130049,-0.000109,-0.130049,7.874917,17,0
4,73.676039,6.859860,81.833707,103.915831,0.402807,-0.000144,0.001584,2.335650,0.402807,3144.952405,...,0.001582,8.053872,2.718047,2.061769,0.411162,-0.000144,0.411162,9.046198,15,1

Model Building

In [ ]:
model = RandomForestClassifier()
model.fit(X_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
predicted_values = pd.DataFrame(le.inverse_transform(y_pred))
predicted_values.head(10)

           0
0   baseline
1   baseline
2     stress
3   baseline
4   baseline
5   baseline
6     stress
7     stress
8  amusement
9  amusement

In [ ]:
accuracy_score(y_test,y_pred)

1.0

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2313
           1       1.00      1.00      1.00      7229
           2       1.00      1.00      1.00      4023

    accuracy                           1.00     13565
   macro avg       1.00      1.00      1.00     13565
weighted avg       1.00      1.00      1.00     13565

In [ ]:
pickle.dump(model, open('model.pkl', 'wb'))

In [ ]:
model_loaded = pickle.load(open('model.pkl','rb'))

In [ ]:
model_loaded.predict(X_test)

array([1, 1, 2, ..., 1, 2, 1])